# Настройка временной зоны
timezone: "Europe/Moscow"
# Настройка кодировки
encoding: "utf-8"

# Коллекции
collections:
  chapters:
    output: true
  socials:
    output: true
  resources:
    output: true


# Настройка макетов по умолчанию
defaults:
  -
    scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapters"
  - 
    scope:
      path: ""                                # Пустая строка означает все файлы в проекте
    values:
      layout: "default"                       # Используемый макет по-умолчанию
      author: "Артем 'InFallen' Нагорный"     # Автор страницы по-умолчанию
      sitename: "InFallen.space"


kramdown:
  hard_wrap: true