# Настройка временной зоны
timezone: "Europe/Moscow"
# Настройка кодировки
encoding: "utf-8"

# Коллекции
collections:
  chapters:
    output: true
    permalink: /:name
  socials:
    output: true
  resources:
    output: true
  jekyllstepbystep:
    output: true
    permalink: /jekyll/stepbystep/:name


# Настройка макетов по умолчанию
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "chapters"
    values:
      layout: "chapter"
  -
    scope:
      path: ""
      type: "jekyllstepbystep"
    values:
      layout: "stepbystep"
  - 
    scope:
      path: ""                                # Пустая строка означает все файлы в проекте
    values:
      layout: "default"                       # Используемый макет по-умолчанию
      author: "Артем 'InFallen' Нагорный"     # Автор страницы по-умолчанию
      sitename: "InFallen.space"